openapi: "3.0.0"
info:
  title: "Practica Encriptacion API"
  version: "1.0.0"
components:
  responses:
    Forbidden:
      description: "Access token is missing or invalid"
    Accepted:
      description: "The request was accepted"
    Created:
      description: "The resource has been created"
    NotFound:
      description: "The resource has been created"
    NotAcceptable:
      description: "The resource has been created"
  securitySchemes:
    BearerAuth:
      type: "http"
      scheme: "bearer"
  schemas:
    Any:
      description: "Any JSON object not defined as schema"
    Sala:
      type: "object"
      properties:
        id:
          type: "number"
          example: 321
        nombre:
          type: "string"
          example: "string"
        password:
          type: "string"
          example: "S3cur3P4s5word!"
          format: "password"
        active:
          type: "boolean"
          example: true
        createdAt:
          type: "string"
          example: "2021-03-23T16:13:08.489+01:00"
          format: "date-time"
        updatedAt:
          type: "string"
          example: "2021-03-23T16:13:08.489+01:00"
          format: "date-time"
      description: "Model"
paths:
  /uploads/*:
    get:
      summary: " (route.ts)"
      description: ""
      parameters: []
      tags:
        - "*"
      responses:
        200:
          description: "OK"
          content:
            application/json: {}
      security: []
  /api/v1/salas/get:
    get:
      summary: " (SalasController::get)"
      description: "OK: { \"status\": \"Éxito\", \"message\": \"Sala encontrada\", \"data\": { \"id\": \"number\", \"nombre\": \"string\", \"password\": \"string\", \"active\": \"boolean\", \"created_at\": \"datetime\", \"updated_at\": \"datetime\" } }"
      parameters: []
      tags:
        - "V1"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Éxito"
                message: "Sala encontrada"
                data:
                  id: "number"
                  nombre: "string"
                  password: "string"
                  active: "boolean"
                  created_at: "datetime"
                  updated_at: "datetime"
          description: "OK: { \"status\": \"Éxito\", \"message\": \"Sala encontrada\", \"data\": { \"id\": \"number\", \"nombre\": \"string\", \"password\": \"string\", \"active\": \"boolean\", \"created_at\": \"datetime\", \"updated_at\": \"datetime\" } }"
        404:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Éxito"
                message: "Sala no encontrada"
                data: "null"
          description: "Not Found: { \"status\": \"Éxito\", \"message\": \"Sala no encontrada\", \"data\": \"null\" }"
      security: []
  /api/v1/salas/get/{id}:
    get:
      summary: " (SalasController::getId)"
      description: ""
      parameters:
        - in: "path"
          name: "id"
          schema:
            type: "string"
          required: true
      tags:
        - "V1"
      responses:
        200:
          description: "OK"
          content:
            application/json: {}
      security: []
  /api/v1/salas/create:
    post:
      summary: " (SalasController::create)"
      description: "Create a new sala"
      parameters: []
      tags:
        - "V1"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Éxito"
                message: "Sala creada"
                data: "null"
          description: "OK: { \"status\": \"Éxito\", \"message\": \"Sala creada\", \"data\": \"null\" }"
        400:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Error"
                message: "message validator"
                data:
                  field: "field"
                  rule: "rule"
          description: "Bad Request: { \"status\": \"Error\", \"message\": \"message validator\", \"data\": { \"field\": \"field\", \"rule\": \"rule\" } }"
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
            example:
              nombre: "string"
              password: "string"
  /api/v1/salas/update/{id}:
    put:
      summary: "Update v1 (SalasController::update)"
      description: "Update a sala"
      parameters:
        - in: "path"
          name: "id"
          schema:
            type: "string"
          required: true
      tags:
        - "V1"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Éxito"
                message: "Sala actualizada"
                data: "null"
          description: "OK: { \"status\": \"Éxito\", \"message\": \"Sala actualizada\", \"data\": \"null\" }"
        400:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Error"
                message: "message validator"
                data:
                  field: "field"
                  rule: "rule"
          description: "Bad Request: { \"status\": \"Error\", \"message\": \"message validator\", \"data\": { \"field\": \"field\", \"rule\": \"rule\" } }"
        404:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Éxito"
                message: "Sala no encontrada"
                data: "null"
          description: "Not Found: { \"status\": \"Éxito\", \"message\": \"Sala no encontrada\", \"data\": \"null\" }"
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
            example:
              nombre: "string"
              password: "string"
  /api/v1/salas/delete/{id}:
    delete:
      summary: " (SalasController::delete)"
      description: "Delete a sala"
      parameters:
        - in: "path"
          name: "id"
          schema:
            type: "string"
          required: true
      tags:
        - "V1"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Éxito"
                message: "Sala desactivada o Sala activada"
                data: "null"
          description: "OK: { \"status\": \"Éxito\", \"message\": \"Sala desactivada o Sala activada\", \"data\": \"null\" }"
        404:
          content:
            application/json:
              schema:
                type: "object"
              example:
                status: "Éxito"
                message: "Sala no encontrada"
                data: "null"
          description: "Not Found: { \"status\": \"Éxito\", \"message\": \"Sala no encontrada\", \"data\": \"null\" }"
      security: []
  /:
    get:
      summary: " (route.ts)"
      description: ""
      parameters: []
      tags: []
      responses:
        200:
          description: "OK"
          content:
            application/json: {}
      security: []
  /request:
    get:
      summary: " (route.ts)"
      description: ""
      parameters: []
      tags: []
      responses:
        200:
          description: "OK"
          content:
            application/json: {}
      security: []
  /api/v1:
    get:
      summary: " (route.ts)"
      description: ""
      parameters: []
      tags:
        - "V1"
      responses:
        200:
          description: "OK"
          content:
            application/json: {}
      security: []
  /*:
    patch:
      summary: " (route.ts)"
      description: ""
      parameters: []
      tags: []
      responses:
        undefined:
          description: "Unknown"
          content:
            application/json: {}
      security: []
      requestBody:
        content:
          application/json: {}
tags:
  - name: "*"
    description: "Everything related to *"
  - name: "V1"
    description: "Everything related to V1"
